# .github/workflows/templates/setup/action.yml
name: 'Setup Environment'
description: 'Sets up the environment for IaC evaluation'
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup Dependencies
      shell: bash
      run: |
        pip install -r requirements.txt
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: eu-west-1
      secrets:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.7'
    - name: Install OpenTofu
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
        chmod +x install-opentofu.sh
        ./install-opentofu.sh --install-method binary
        rm install-opentofu.sh
        tofu --version
    - name: Install AWS CLI
      shell: bash
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version    
    - name: Create results directory structure
      shell: bash
      run: |
        mkdir -p results/static-analysis
        mkdir -p results/deployment
        mkdir -p results/performance
        mkdir -p results/cost-analysis
 
    - name: Upload directory structure as artifact
      uses: actions/upload-artifact@v3
      with:
        name: results-structure
        path: results/