AWSTemplateFormatVersion: '2010-09-09'
Description: '3-Tier Architecture Infrastructure - Compute Stack'

Parameters:
  AppSecurityGroupId:
    Description: Security group ID for application instances
    Type: String

  BastionSecurityGroupId:
    Description: Security group ID for bastion host
    Type: String

  PrivateAppSubnet1Id:
    Description: ID of the first private app subnet
    Type: String

  PrivateAppSubnet2Id:
    Description: ID of the second private app subnet
    Type: String

  PublicSubnet1Id:
    Description: ID of the first public subnet
    Type: String

  PublicSubnet2Id:
    Description: ID of the second public subnet
    Type: String

  KeyName:
    Description: Name of the SSH key pair
    Type: String
    Default: dissertation_key

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro

  AmiId:
    Description: AMI ID for EC2 instances
    Type: String
    Default: ami-0fed63ea358539e44

  SSHPublicKey:
    Description: The SSH public key content
    Type: String
    Default: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeVGiH7I+x4vCfR3e7E0havpo/dr2LqO4AmvIrSX4BqKSwZrVbVVA7GF18pPFURaIX3rj6ZI7iWXD2hIVjSHbu55oBou0QrPmc/4CNhO3+3vlOWtcpsfxlLOlDW5tsvRAPHJA5IXdXkPwGYyndXiWVuQsB7gicC+1WIddvXKHMWMyhxuxuFx+/vGRzvZz0R4h9Dq7s+oRO7fjCwefnOMj7yCZUSaKUUZxH9ZlIxuLuxgcBq7scd1N0yAL/Sj0AOOGLEYkln+0cN4d88lFuN6XmBrOt5DWKoqNGuNGLYqWk4EpY4EMZZQ3RbxTAmfLQ83D92/yKgHWI1VMwAP3SK2J1"

Resources:

  # Create the Key Pair
  DissertationKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref KeyName
      PublicKeyMaterial: !Ref SSHPublicKey

  # Application Server Instances
  ApplicationInstance1:
    Type: AWS::EC2::Instance
    DependsOn: DissertationKeyPair
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref PrivateAppSubnet1Id
      SecurityGroupIds: 
        - !Ref AppSecurityGroupId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          # Log output for better debugging
          exec > >(tee /var/log/user-data.log) 2>&1
          echo "Starting user data execution at $(date)"
          
          # Update and install packages
          yum update -y
          yum install -y httpd mariadb-server php-mbstring php-xml
          
          # Create index.html
          echo '<h1>Hello world from a highly available group of EC2 instances</h1>' > /var/www/html/index.html
          echo '<p>This is instance running in an availability zone.</p>' >> /var/www/html/index.html
          
          # Configure permissions
          usermod -a -G apache ec2-user
          chown -R ec2-user:apache /var/www
          chmod 2775 /var/www
          find /var/www -type d -exec chmod 2775 {} \;
          find /var/www -type f -exec chmod 0664 {} \;
          
          # Start and enable Apache
          systemctl start httpd
          systemctl enable httpd
          
          # Log completion
          echo "User data execution completed at $(date)"
      Tags:
        - Key: Name
          Value: CF-application-server-1
        - Key: AZ
          Value: az1
        - Key: Environment
          Value: Production
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Tier
          Value: Application
        - Key: Role
          Value: WebServer
        - Key: Project
          Value: 3TierArchitecture
        - Key: Owner
          Value: Infrastructure

  ApplicationInstance2:
    Type: AWS::EC2::Instance
    DependsOn: DissertationKeyPair
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref PrivateAppSubnet2Id
      SecurityGroupIds: 
        - !Ref AppSecurityGroupId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          # Log output for better debugging
          exec > >(tee /var/log/user-data.log) 2>&1
          echo "Starting user data execution at $(date)"
          
          # Update and install packages
          yum update -y
          yum install -y httpd mariadb-server php-mbstring php-xml
          
          # Create index.html
          echo '<h1>Hello world from a highly available group of EC2 instances</h1>' > /var/www/html/index.html
          echo '<p>This is instance running in an availability zone.</p>' >> /var/www/html/index.html
          
          # Configure permissions
          usermod -a -G apache ec2-user
          chown -R ec2-user:apache /var/www
          chmod 2775 /var/www
          find /var/www -type d -exec chmod 2775 {} \;
          find /var/www -type f -exec chmod 0664 {} \;
          
          # Start and enable Apache
          systemctl start httpd
          systemctl enable httpd
          
          # Log completion
          echo "User data execution completed at $(date)"
      Tags:
        - Key: Name
          Value: CF-application-server-2
        - Key: AZ
          Value: az2
        - Key: Environment
          Value: Production
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Tier
          Value: Application
        - Key: Role
          Value: WebServer
        - Key: Project
          Value: 3TierArchitecture
        - Key: Owner
          Value: Infrastructure

  # Bastion Host
  BastionHost:
    Type: AWS::EC2::Instance
    DependsOn: DissertationKeyPair
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref PublicSubnet1Id
          GroupSet: 
            - !Ref BastionSecurityGroupId
          AssociatePublicIpAddress: true
      Tags:
        - Key: Name
          Value: CF-bastion-host-1
        - Key: AZ
          Value: az1
        - Key: Environment
          Value: Production
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Tier
          Value: Presentation
        - Key: Role
          Value: BastionHost
        - Key: Project
          Value: 3TierArchitecture
        - Key: Owner
          Value: Infrastructure

Outputs:
  KeyPairName:
    Description: Name of the created key pair
    Value: !Ref DissertationKeyPair
    Export:
      Name: !Sub "${AWS::StackName}-KeyPairName"

  AppInstance1Id:
    Description: ID of the first application instance
    Value: !Ref ApplicationInstance1
    Export:
      Name: !Sub "${AWS::StackName}-AppInstance1Id"

  AppInstance2Id:
    Description: ID of the second application instance
    Value: !Ref ApplicationInstance2
    Export:
      Name: !Sub "${AWS::StackName}-AppInstance2Id"

  BastionPublicIP:
    Description: Public IP address of the bastion host
    Value: !GetAtt BastionHost.PublicIp
    Export:
      Name: !Sub "${AWS::StackName}-BastionPublicIP"
