# .github/workflows/deploy-tf-workflow.yml

name: Terraform Deployment Analysis

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
        
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Install dependencies
        run: |
          pip install boto3 awscli
          mkdir -p results/deployment
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"
          
      - name: Record start time
        run: |
          echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
          echo "Deployment starting at $(date)"
      
      - name: Deploy with Terraform
        id: terraform-deploy
        run: |
          cd infrastructure/terraform
          
          # Measure init time
          INIT_START=$(date +%s)
          terraform init
          INIT_END=$(date +%s)
          
          # Measure apply time
          APPLY_START=$(date +%s)
          terraform apply -auto-approve
          APPLY_STATUS=$?
          APPLY_END=$(date +%s)
          
          # Calculate times
          INIT_DURATION=$((INIT_END - INIT_START))
          APPLY_DURATION=$((APPLY_END - APPLY_START))
          TOTAL_DURATION=$((APPLY_END - INIT_START))
          
          echo "Terraform init time: ${INIT_DURATION}s"
          echo "Terraform apply time: ${APPLY_DURATION}s"
          echo "Total deployment time: ${TOTAL_DURATION}s"
          
          # Create deployment report
          mkdir -p ../../results/deployment
          cat > ../../results/deployment/terraform_deployment_report.json << EOF
          {
            "tool": "terraform",
            "init_time_seconds": $INIT_DURATION,
            "apply_time_seconds": $APPLY_DURATION,
            "total_time_seconds": $TOTAL_DURATION,
            "success": $([ $APPLY_STATUS -eq 0 ] && echo "true" || echo "false"),
            "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          }
          EOF
          
          # Let the workflow know if this succeeded
          if [ $APPLY_STATUS -eq 0 ]; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
          fi
          
      - name: Upload Deployment Results
        uses: actions/upload-artifact@v4
        with:
          name: deployment-results-terraform
          path: results/deployment/