# .github/workflows/iac-evaluation.yml

name: IaC Tools Evaluation

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - '**'  # This will match all branches
  # schedule:
  #   - cron: '0 0 * * 0'  # Weekly run

jobs:
  setup:
    uses: ./.github/workflows/setup-workflow.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # static-analysis:
  #   needs: setup
  #   strategy:
  #     matrix:
  #       tool: [terraform, cloudformation, opentofu]
  #   uses: ./.github/workflows/static-analysis-workflow.yml
  #   with:
  #     tool: ${{ matrix.tool }}
  #   secrets:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # deployment:
  #   needs: static-analysis
  #   strategy:
  #     matrix:
  #       tool: [terraform, cloudformation, opentofu]
  #   uses: ./.github/workflows/deployment-workflow.yml
  #   with:
  #     tool: ${{ matrix.tool }}
  #   secrets:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # performance:
  #   needs: deployment
  #   strategy:
  #     matrix:
  #       tool: [terraform, cloudformation, opentofu]
  #   uses: ./.github/workflows/performance-workflow.yml
  #   with:
  #     tool: ${{ matrix.tool }}
  #   secrets:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # cost-analysis:
  #   needs: deployment
  #   strategy:
  #     matrix:
  #       tool: [terraform, cloudformation, opentofu]
  #   uses: ./.github/workflows/cost-analysis-workflow.yml
  #   with:
  #     tool: ${{ matrix.tool }}
  #   secrets:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # report:
  #   needs: [static-analysis, deployment, performance, cost-analysis]
  #   uses: ./.github/workflows/report-generation-workflow.yml
  #   secrets:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}