# .github/workflows/iac-evaluation.yml

name: IaC Tools Evaluation

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - '**'  # This will match all branches
  # schedule:
  #   - cron: '0 0 * * 0'  # Weekly run

jobs:
  setup:
    uses: ./.github/workflows/setup-workflow.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  complexity:
    needs: setup
    strategy:
      matrix:
        tool: [terraform, cloudformation, opentofu]
    uses: ./.github/workflows/complexity-workflow.yml
    with:
      tool: ${{ matrix.tool }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  security:
    needs: complexity
    strategy:
      matrix:
        tool: [terraform, cloudformation, opentofu]
    uses: ./.github/workflows/security-workflow.yml
    with:
      tool: ${{ matrix.tool }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  cost:
    needs: security
    strategy:
      matrix:
        tool: [terraform, cloudformation, opentofu]
    uses: ./.github/workflows/cost-workflow.yml
    with:
      tool: ${{ matrix.tool }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

  # deployment:
  #   needs: cost
  #   strategy:
  #     matrix:
  #       tool: [terraform, cloudformation, opentofu]
  #   uses: ./.github/workflows/deployment-workflow.yml
  #   with:
  #     tool: ${{ matrix.tool }}
  #   secrets:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # report:
  #   needs: [complexity, security, deployment, performance, cost]
  #   uses: ./.github/workflows/report-workflow.yml
  #   secrets:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}