# .github/workflows/iac-evaluation.yml

name: IaC Tools Evaluation

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - '**'  # This will match all branches

jobs:
  complexity:
    # needs: setup
    strategy:
      matrix:
        tool: [terraform, cloudformation, opentofu]
    uses: ./.github/workflows/complexity-workflow.yml
    with:
      tool: ${{ matrix.tool }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  security:
    needs: complexity
    strategy:
      matrix:
        tool: [terraform, cloudformation, opentofu]
    uses: ./.github/workflows/security-workflow.yml
    with:
      tool: ${{ matrix.tool }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  cost:
    needs: security
    strategy:
      matrix:
        tool: [terraform, cloudformation, opentofu]
    uses: ./.github/workflows/cost-workflow.yml
    with:
      tool: ${{ matrix.tool }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

  terraform-deployment:
    needs: cost
    uses: ./.github/workflows/deploy-tf-workflow.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  opentofu-deployment:
    needs: cost
    uses: ./.github/workflows/deploy-opentofu-workflow.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  cloudformation-deployment:
    needs: cost
    uses: ./.github/workflows/deploy-cloudformation-workflow.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  terraform-teardown:
    needs: [complexity, security,cost, terraform-deployment]
    uses: ./.github/workflows/teardown-tf-workflow.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  opentofu-teardown:
    needs: [complexity, security,cost,opentofu-deployment]
    uses: ./.github/workflows/teardown-opentofu-workflow.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  cloudformation-teardown:
    needs: [complexity, security,cost,cloudformation-deployment]
    uses: ./.github/workflows/teardown-cloudformation-workflow.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}