# .github/workflows/report-workflow.yml

name: Final Report Generation

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: terraform
        
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: Install report generation dependencies
        run: |
          pip install jinja2 pandas matplotlib markdown pygments
      
      ### Complexity    
      - name: Download complexity artifacts
        uses: actions/download-artifact@v3
        with:
          name: complexity-results-terraform
          path: results/complexity/
          
      - name: Download complexity artifacts
        uses: actions/download-artifact@v3
        with:
          name: complexity-results-cloudformation
          path: results/complexity/
          
      - name: Download complexity artifacts
        uses: actions/download-artifact@v3
        with:
          name: complexity-results-opentofu
          path: results/complexity/
      
      ### Security 
      - name: Download security artifacts
        uses: actions/download-artifact@v3
        with:
          name: security-results-terraform
          path: results/security/
          
      - name: Download security artifacts
        uses: actions/download-artifact@v3
        with:
          name: security-results-cloudformation
          path: results/security/
          
      - name: Download security artifacts
        uses: actions/download-artifact@v3
        with:
          name: security-results-opentofu
          path: results/security/
      
      ### Cost    
      - name: Download cost artifacts
        uses: actions/download-artifact@v3
        with:
          name: cost-results-terraform
          path: results/cost/
          
      - name: Download cost artifacts
        uses: actions/download-artifact@v3
        with:
          name: cost-results-cloudformation
          path: results/cost/
          
      - name: Download cost artifacts
        uses: actions/download-artifact@v3
        with:
          name: cost-results-opentofu
          path: results/cost/
      
      ### Deployment
      - name: Download deployment artifacts - Terraform
        uses: actions/download-artifact@v3
        with:
          name: deployment-results-terraform
          path: results/deployment/
          
      - name: Download deployment artifacts - CloudFormation
        uses: actions/download-artifact@v3
        with:
          name: deployment-results-cloudformation
          path: results/deployment/
          
      - name: Download deployment artifacts - OpenTofu
        uses: actions/download-artifact@v3
        with:
          name: deployment-results-opentofu
          path: results/deployment/
          
          
      - name: Create report output directory
        run: |
          mkdir -p results/final-report
          mkdir -p results/final-report/images
          mkdir -p results/final-report/charts
          mkdir -p results/final-report/data
          
      - name: Generate final report
        run: |
          # Generate the final comparison report
          python scripts/report_generator.py \
            --complexity-dir results/complexity \
            --security-dir results/security \
            --deployment-dir results/deployment \
            --cost-dir results/cost \
            --output-dir results/final-report
          
      - name: Upload Final Report
        uses: actions/upload-artifact@v4
        with:
          name: iac-evaluation-report
          path: results/final-report/
          
      # - name: Deploy to GitHub Pages
      #   if: github.ref == 'refs/heads/main'
      #   uses: actions/deploy-pages@v2
      #   with:
      #     artifact_name: iac-evaluation-report