# .github/workflows/security-workflow.yml

name: Security Analysis Workflow

on:
  workflow_call:
    inputs:
      tool:
        required: true
        type: string
        description: 'The IaC tool to analyse for security (terraform, cloudformation, opentofu)'
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          ref: terraform
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Create Results Directory
      run: |
        mkdir -p results/security
        chmod 777 results/security

    - name: Install dependencies
      run: |
        # Install tools
        python -m pip install --upgrade pip
    
    - name: Determine Checkov Checks
      id: select-checks
      run: |
        if [ "${{ inputs.tool }}" == "cloudformation" ]; then
          # CloudFormation-specific checks
          CHECKOV_CHECKS="CKV_AWS_2,CKV_AWS_3,CKV_AWS_5,CKV_AWS_6,CKV_AWS_7,CKV_AWS_16,CKV_AWS_17,CKV_AWS_18,CKV_AWS_19,CKV_AWS_20,CKV_AWS_21,CKV_AWS_23,CKV_AWS_24,CKV_AWS_25,CKV_AWS_26,CKV_AWS_27,CKV_AWS_28,CKV_AWS_33,CKV_AWS_34,CKV_AWS_35,CKV_AWS_40,CKV_AWS_42,CKV_AWS_45,CKV_AWS_53,CKV_AWS_54,CKV_AWS_58,CKV_AWS_59,CKV_AWS_60,CKV_AWS_61,CKV_AWS_62,CKV_AWS_63"
        else
          # Terraform/OpenTofu checks
          CHECKOV_CHECKS="CKV_AWS_1,CKV_AWS_2,CKV_AWS_3,CKV_AWS_5,CKV_AWS_6,CKV_AWS_7,CKV_AWS_8,CKV_AWS_16,CKV_AWS_17,CKV_AWS_18,CKV_AWS_19,CKV_AWS_20,CKV_AWS_21,CKV_AWS_23,CKV_AWS_24,CKV_AWS_25,CKV_AWS_26,CKV_AWS_27,CKV_AWS_28,CKV_AWS_32,CKV_AWS_33,CKV_AWS_34,CKV_AWS_35,CKV_AWS_36,CKV_AWS_40,CKV_AWS_42,CKV_AWS_45,CKV_AWS_53,CKV_AWS_54,CKV_AWS_58,CKV_AWS_59,CKV_AWS_60,CKV_AWS_61,CKV_AWS_62,CKV_AWS_63"
        fi
        echo "checks=$CHECKOV_CHECKS" >> $GITHUB_OUTPUT
      
    - name: Run Checkov Security Scan
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: infrastructure/${{ inputs.tool }}
        output_format: json
        output_file_path: results/security/${{ inputs.tool }}_checkov_results.json,
        check: ${{ steps.select-checks.outputs.checks }}
        skip_framework: dockerfile,secrets,helm,kustomize
        quiet: false
        soft_fail: true

    - name: Debug Checkov Results
      run: |
        echo "Checkov results file contents:"
        cat results/security/${{ inputs.tool }}_checkov_results.json || echo "File not found"
        echo "Directory contents:"
        ls -l results/security
    
    - name: Analyse Security Findings
      run: |
        python scripts/analysers/security_analyser.py \
          --tool ${{ inputs.tool }} \
          --check-file results/security/${{ inputs.tool }}_checkov_results.json \
          --output results/security/${{ inputs.tool }}_security_report.json
    
    - name: Upload Security Reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports-${{ inputs.tool }}
        path: results/security/