# .github/workflows/security-workflow.yml

name: Security Analysis

on:
  workflow_call:
    inputs:
      tool:
        required: true
        type: string
        description: 'The IaC tool to analyse for security (terraform, cloudformation, opentofu)'
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  analyse-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          
      - name: Ensure results directory exists
        run: |
          mkdir -p results/security
      
      - name: Install Checkov
        run: |
          pip install checkov
          checkov --version
      
      - name: Run Security Analysis
        run: |
          # Determine which directory to analyse
          if [ "${{ inputs.tool }}" == "terraform" ]; then
            IaC_DIR="infrastructure/terraform"
            FRAMEWORK="terraform"
          elif [ "${{ inputs.tool }}" == "opentofu" ]; then
            IaC_DIR="infrastructure/opentofu"
            FRAMEWORK="terraform" # Use terraform framework for OpenTofu
          elif [ "${{ inputs.tool }}" == "cloudformation" ]; then
            IaC_DIR="infrastructure/cloudformation"
            FRAMEWORK="cloudformation"
          fi
          
          # Run Checkov security checks
          echo "Running security analysis for ${{ inputs.tool }}..."
          
          # AWS security best practices
          checkov -d $IaC_DIR --framework $FRAMEWORK --check AWS --output json > results/security/${{ inputs.tool }}_aws_checks.json
          
          # IAM security checks
          checkov -d $IaC_DIR --framework $FRAMEWORK --check IAM --output json > results/security/${{ inputs.tool }}_iam_checks.json
          
          # Network security checks
          checkov -d $IaC_DIR --framework $FRAMEWORK --check NETWORKS --output json > results/security/${{ inputs.tool }}_network_checks.json
          
          # Encryption checks
          checkov -d $IaC_DIR --framework $FRAMEWORK --check ENCRYPTION --output json > results/security/${{ inputs.tool }}_encryption_checks.json
          
          # Generate summary
          python scripts/analysers/security_analyser.py --tool ${{ inputs.tool }} \
            --aws-checks results/security/${{ inputs.tool }}_aws_checks.json \
            --iam-checks results/security/${{ inputs.tool }}_iam_checks.json \
            --network-checks results/security/${{ inputs.tool }}_network_checks.json \
            --encryption-checks results/security/${{ inputs.tool }}_encryption_checks.json \
            --output results/security/${{ inputs.tool }}_security_report.json
    
      - name: Upload Security Analysis Results
        uses: actions/upload-artifact@v4
        with:
          name: security-results-${{ inputs.tool }}
          path: results/security/